# Travis CI
sudo: false

language: ruby

rvm:
  - 2.3.1
  - 2.3.0

matrix:
  include:
    - # Ruby 2.2.5
      rvm: 2.2.5
      env: BUNTO_VERSION=3.2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - BUNTO_VERSION=3.2.1

cache: bundler

before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild

script: ./script/cibuild

notifications:
  email: false
